name: Checks

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - go.mod
      - go.sum
      - internal/**

jobs:
  code-formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: "true"
  run-go-vet:
    name: Go Vet
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: "true"
  code-linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: "true"
  test-coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: "true"
  run-go-unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: "true"
